In [1]:
import pandas as pd #need to run everytime

In [2]:
import numpy as np #import numpy

In [4]:
#copy and view methods of numpy
a1 = np.array([1,2,3,4,5,6])
x = a1.copy() #copy one time only

a1[1] = 24 #appears in original only

print("Original Array: ",a1)
print("Copy Array: ",x)

Original Array:  [ 1 24  3  4  5  6]
Copy Array:  [1 2 3 4 5 6]


In [7]:
#copy and view methods of numpy
a2 = np.array([1,2,3,4,5,6])
x = a2.view() #view array

a2[0] = 32 #appears in both

print("Original Array: ",a2)
print("Copy Array: ",x)

Original Array:  [32  2  3  4  5  6]
Copy Array:  [32  2  3  4  5  6]


In [8]:
#join array
a2 = np.array([1,2,3,4,5,6,7])
a3 = np.array([8,9])

z = np.concatenate((a2,a3)) #combine 2 array
print(z)

[1 2 3 4 5 6 7 8 9]


In [10]:
#random number array
from numpy import random

arr = random.randint(20) #one value only, ending value, 20 = 0 to 20 range

print(arr) #everytime run, it will give different numbers

4


In [11]:
y = random.randint(100,size=(3,5)) #0 to 100 range in (row,col)
print(y)

[[ 2 82 84 17 18]
 [86 13 96 25 23]
 [93 23  2 72  9]]
