In [1]:
import pandas as pd #need to run everytime

In [2]:
df1 = pd.read_json("persons.json")
df1

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [3]:
data = pd.read_csv("Bengaluru_House_Data.csv")
data

area_type   availability                  location   
0      Super built-up  Area         19-Dec  Electronic City Phase II  \
1                Plot  Area  Ready To Move          Chikka Tirupathi   
2            Built-up  Area  Ready To Move               Uttarahalli   
3      Super built-up  Area  Ready To Move        Lingadheeranahalli   
4      Super built-up  Area  Ready To Move                  Kothanur   
...                     ...            ...                       ...   
13315        Built-up  Area  Ready To Move                Whitefield   
13316  Super built-up  Area  Ready To Move             Richards Town   
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar   
13318  Super built-up  Area         18-Jun           Padmanabhanagar   
13319  Super built-up  Area  Ready To Move              Doddathoguru   

            size  society total_sqft  bath  balcony   price  
0          2 BHK  Coomee        1056   2.0      1.0   39.07  
1      4 Bedroom  Theanmp       2600   5.0      3.0  120.00  
2          3 BHK      NaN       1440   2.0      3.0   62.00  
3          3 BHK  Soiewre       1521   3.0      1.0   95.00  
4          2 BHK      NaN       1200   2.0      1.0   51.00  
...          ...      ...        ...   ...      ...     ...  
13315  5 Bedroom  ArsiaEx       3453   4.0      0.0  231.00  
13316      4 BHK      NaN       3600   5.0      NaN  400.00  
13317      2 BHK  Mahla T       1141   2.0      1.0   60.00  
13318      4 BHK  SollyCl       4689   4.0      1.0  488.00  
13319      1 BHK      NaN        550   1.0      1.0   17.00  

[13320 rows x 9 columns]

In [4]:
#check a shape of data
data.shape #count of (rows, columns)
#data is variable

(13320, 9)

In [5]:
#check null values from data
data.isnull() #shows in boolean result
#false - data is there
#true - data is not there

area_type  availability  location   size  society  total_sqft   bath   
0          False         False     False  False    False       False  False  \
1          False         False     False  False    False       False  False   
2          False         False     False  False     True       False  False   
3          False         False     False  False    False       False  False   
4          False         False     False  False     True       False  False   
...          ...           ...       ...    ...      ...         ...    ...   
13315      False         False     False  False    False       False  False   
13316      False         False     False  False     True       False  False   
13317      False         False     False  False    False       False  False   
13318      False         False     False  False    False       False  False   
13319      False         False     False  False     True       False  False   

       balcony  price  
0        False  False  
1        False  False  
2        False  False  
3        False  False  
4        False  False  
...        ...    ...  
13315    False  False  
13316     True  False  
13317    False  False  
13318    False  False  
13319    False  False  

[13320 rows x 9 columns]

In [6]:
#check null values according to column wise
data.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [7]:
#check total null values
data.isnull().sum().sum()

6201

In [9]:
#fill null values by using 0
data1 = data.fillna(value=0)
data1

area_type   availability                  location   
0      Super built-up  Area         19-Dec  Electronic City Phase II  \
1                Plot  Area  Ready To Move          Chikka Tirupathi   
2            Built-up  Area  Ready To Move               Uttarahalli   
3      Super built-up  Area  Ready To Move        Lingadheeranahalli   
4      Super built-up  Area  Ready To Move                  Kothanur   
...                     ...            ...                       ...   
13315        Built-up  Area  Ready To Move                Whitefield   
13316  Super built-up  Area  Ready To Move             Richards Town   
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar   
13318  Super built-up  Area         18-Jun           Padmanabhanagar   
13319  Super built-up  Area  Ready To Move              Doddathoguru   

            size  society total_sqft  bath  balcony   price  
0          2 BHK  Coomee        1056   2.0      1.0   39.07  
1      4 Bedroom  Theanmp       2600   5.0      3.0  120.00  
2          3 BHK        0       1440   2.0      3.0   62.00  
3          3 BHK  Soiewre       1521   3.0      1.0   95.00  
4          2 BHK        0       1200   2.0      1.0   51.00  
...          ...      ...        ...   ...      ...     ...  
13315  5 Bedroom  ArsiaEx       3453   4.0      0.0  231.00  
13316      4 BHK        0       3600   5.0      0.0  400.00  
13317      2 BHK  Mahla T       1141   2.0      1.0   60.00  
13318      4 BHK  SollyCl       4689   4.0      1.0  488.00  
13319      1 BHK        0        550   1.0      1.0   17.00  

[13320 rows x 9 columns]

In [10]:
data1.isnull().sum().sum() #checking if there are no more null values left after replacing to 0

0

In [11]:
#fill null values by using previous value
data2 = data.fillna(method='pad')
data2

area_type   availability                  location   
0      Super built-up  Area         19-Dec  Electronic City Phase II  \
1                Plot  Area  Ready To Move          Chikka Tirupathi   
2            Built-up  Area  Ready To Move               Uttarahalli   
3      Super built-up  Area  Ready To Move        Lingadheeranahalli   
4      Super built-up  Area  Ready To Move                  Kothanur   
...                     ...            ...                       ...   
13315        Built-up  Area  Ready To Move                Whitefield   
13316  Super built-up  Area  Ready To Move             Richards Town   
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar   
13318  Super built-up  Area         18-Jun           Padmanabhanagar   
13319  Super built-up  Area  Ready To Move              Doddathoguru   

            size  society total_sqft  bath  balcony   price  
0          2 BHK  Coomee        1056   2.0      1.0   39.07  
1      4 Bedroom  Theanmp       2600   5.0      3.0  120.00  
2          3 BHK  Theanmp       1440   2.0      3.0   62.00  
3          3 BHK  Soiewre       1521   3.0      1.0   95.00  
4          2 BHK  Soiewre       1200   2.0      1.0   51.00  
...          ...      ...        ...   ...      ...     ...  
13315  5 Bedroom  ArsiaEx       3453   4.0      0.0  231.00  
13316      4 BHK  ArsiaEx       3600   5.0      0.0  400.00  
13317      2 BHK  Mahla T       1141   2.0      1.0   60.00  
13318      4 BHK  SollyCl       4689   4.0      1.0  488.00  
13319      1 BHK  SollyCl        550   1.0      1.0   17.00  

[13320 rows x 9 columns]

In [12]:
data2.isnull().sum().sum() #checking if there are no more null values left after replacing to previous value

0

In [13]:
data2.isnull().sum()

area_type       0
availability    0
location        0
size            0
society         0
total_sqft      0
bath            0
balcony         0
price           0
dtype: int64

In [14]:
#fill null values by using next value
data3 = data.fillna(method='bfill')
data3

area_type   availability                  location   
0      Super built-up  Area         19-Dec  Electronic City Phase II  \
1                Plot  Area  Ready To Move          Chikka Tirupathi   
2            Built-up  Area  Ready To Move               Uttarahalli   
3      Super built-up  Area  Ready To Move        Lingadheeranahalli   
4      Super built-up  Area  Ready To Move                  Kothanur   
...                     ...            ...                       ...   
13315        Built-up  Area  Ready To Move                Whitefield   
13316  Super built-up  Area  Ready To Move             Richards Town   
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar   
13318  Super built-up  Area         18-Jun           Padmanabhanagar   
13319  Super built-up  Area  Ready To Move              Doddathoguru   

            size  society total_sqft  bath  balcony   price  
0          2 BHK  Coomee        1056   2.0      1.0   39.07  
1      4 Bedroom  Theanmp       2600   5.0      3.0  120.00  
2          3 BHK  Soiewre       1440   2.0      3.0   62.00  
3          3 BHK  Soiewre       1521   3.0      1.0   95.00  
4          2 BHK  DuenaTa       1200   2.0      1.0   51.00  
...          ...      ...        ...   ...      ...     ...  
13315  5 Bedroom  ArsiaEx       3453   4.0      0.0  231.00  
13316      4 BHK  Mahla T       3600   5.0      1.0  400.00  
13317      2 BHK  Mahla T       1141   2.0      1.0   60.00  
13318      4 BHK  SollyCl       4689   4.0      1.0  488.00  
13319      1 BHK      NaN        550   1.0      1.0   17.00  

[13320 rows x 9 columns]

In [16]:
data3.isnull().sum() #remains one not filled because of the last row has no next value

area_type       0
availability    0
location        0
size            0
society         1
total_sqft      0
bath            0
balcony         0
price           0
dtype: int64

In [18]:
#fill null values with my own value each
data4 = data.fillna({
  'society':'vanessa', #column name, value you want
  'balcony':'lino'
})  #dictionary
data4

area_type   availability                  location   
0      Super built-up  Area         19-Dec  Electronic City Phase II  \
1                Plot  Area  Ready To Move          Chikka Tirupathi   
2            Built-up  Area  Ready To Move               Uttarahalli   
3      Super built-up  Area  Ready To Move        Lingadheeranahalli   
4      Super built-up  Area  Ready To Move                  Kothanur   
...                     ...            ...                       ...   
13315        Built-up  Area  Ready To Move                Whitefield   
13316  Super built-up  Area  Ready To Move             Richards Town   
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar   
13318  Super built-up  Area         18-Jun           Padmanabhanagar   
13319  Super built-up  Area  Ready To Move              Doddathoguru   

            size  society total_sqft  bath balcony   price  
0          2 BHK  Coomee        1056   2.0     1.0   39.07  
1      4 Bedroom  Theanmp       2600   5.0     3.0  120.00  
2          3 BHK  vanessa       1440   2.0     3.0   62.00  
3          3 BHK  Soiewre       1521   3.0     1.0   95.00  
4          2 BHK  vanessa       1200   2.0     1.0   51.00  
...          ...      ...        ...   ...     ...     ...  
13315  5 Bedroom  ArsiaEx       3453   4.0     0.0  231.00  
13316      4 BHK  vanessa       3600   5.0    lino  400.00  
13317      2 BHK  Mahla T       1141   2.0     1.0   60.00  
13318      4 BHK  SollyCl       4689   4.0     1.0  488.00  
13319      1 BHK  vanessa        550   1.0     1.0   17.00  

[13320 rows x 9 columns]

In [19]:
#convert null values into mean values - statistics
data5 = data.fillna(value=data['balcony'].mean()) #column name, mean() will calculate all the values
data5

area_type   availability                  location   
0      Super built-up  Area         19-Dec  Electronic City Phase II  \
1                Plot  Area  Ready To Move          Chikka Tirupathi   
2            Built-up  Area  Ready To Move               Uttarahalli   
3      Super built-up  Area  Ready To Move        Lingadheeranahalli   
4      Super built-up  Area  Ready To Move                  Kothanur   
...                     ...            ...                       ...   
13315        Built-up  Area  Ready To Move                Whitefield   
13316  Super built-up  Area  Ready To Move             Richards Town   
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar   
13318  Super built-up  Area         18-Jun           Padmanabhanagar   
13319  Super built-up  Area  Ready To Move              Doddathoguru   

            size   society total_sqft  bath   balcony   price  
0          2 BHK   Coomee        1056   2.0  1.000000   39.07  
1      4 Bedroom   Theanmp       2600   5.0  3.000000  120.00  
2          3 BHK  1.584376       1440   2.0  3.000000   62.00  
3          3 BHK   Soiewre       1521   3.0  1.000000   95.00  
4          2 BHK  1.584376       1200   2.0  1.000000   51.00  
...          ...       ...        ...   ...       ...     ...  
13315  5 Bedroom   ArsiaEx       3453   4.0  0.000000  231.00  
13316      4 BHK  1.584376       3600   5.0  1.584376  400.00  
13317      2 BHK   Mahla T       1141   2.0  1.000000   60.00  
13318      4 BHK   SollyCl       4689   4.0  1.000000  488.00  
13319      1 BHK  1.584376        550   1.0  1.000000   17.00  

[13320 rows x 9 columns]

#mathematical part - numpy
#assignment, combination of pandas and numpy

In [20]:
pip install numpy #already satisfy the requirement


[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [21]:
import numpy as np #import numpy

In [22]:
#create array, array() - function in numpy
#np - alias or short term of library of numpy
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr)) #ndarray - multiple dimensional array

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [23]:
#0D array - 1 Dimensional array 
arr1 = np.array(32) #one value in an array
print(arr1)

32


In [24]:
#2D array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [25]:
#3D array
arr3 = np.array([[[1,2,3],[5,6,7]],[[1,2,3],[4,5,6]]]) #bracket should be perfect
print(arr3)

[[[1 2 3]
  [5 6 7]]

 [[1 2 3]
  [4 5 6]]]
